os:
  # edit: 'nvr -O $(pwd)/{{filename}}'
  # editAtLine: 'nvr -O +{{line}} $(pwd)/{{filename}}'
  # edit: 'nvr --remote-send "<F1>:e $(pwd)/{{filename}}<cr>"'
  # edit: 'nvr -c "FloatermHide" && nvr -c "e $(pwd)/{{filename}}"'
  # edit: 'nvr -c "FloatermHide" && nvr --remote-send ":e {{filename}}<cr>"'
  edit: 'nvr -c "FloatermHide" && nvr -c "e {{filename}}"'
  editAtLine: 'nvr -c "FloatermHide" && nvr -c "e +{{line}} {{filename}}"'
gui:
  theme:
    selectedLineBgColor:
      - default
customCommands:
  - key: 'C'
    context: 'localBranches'
    # prompts:
    #   - type: 'menu'
    #     title: 'What kind of branch is it?'
    #     key: 'BranchType'
    #     options:
    #       - name: 'ta'
    #         description: 'Team Assurance Branch'
    #         value: 'TA'
    #       - name: 'feature'
    #         description: 'A feature branch'
    #         value: 'tom.levt/feat/'
    #       - name: 'fix'
    #         description: 'A fix branch'
    #         value: 'tom.levt/fix/'
    #   - type: 'input'
    #     title: 'What is the new branch name?'
    #     key: 'BranchName'
    #     initialValue: ''
    # command: "git checkout -b {{.Form.BranchType}}{{.Form.BranchName}}"
    loadingText: 'Creating branch'
    prompts:
      - type: 'input'
        title: 'What is the new branch name?'
        initialValue: 'tom.levt/feat/'
    description: 'Checkout under your name'
    command: "git checkout -b {{index .PromptResponses 0}}"
  - key: 'C'
    context: 'files'
    loadingText: 'Creating commit'
    prompts:
      - type: 'input'
        title: 'What is the new commit'
        key: 'CommitName'
        initialValue: ''
    description: 'Shortcut commit'
    command: "git commit -m '{{.Form.CommitName}}'"
  # - key: 'P'
  #   description: 'Commit with prefix from last commit'
  #   context: 'files'
  #   command: >
  #     bash -c '
  #     PREFIX=$(git rev-parse --abbrev-ref HEAD | sed -E "s|^tom.levt/(feat/).*$|\1|" | sed -E "s|^(TA-[0-9]+).*$|\1|");
  #     read -p "Enter commit message: " MSG;
  #     git commit -m "$PREFIX $MSG"'
  - key: 'F'
    context: 'global'
    description: 'Pull the latest target branch to your branch'
    command: "git pull --rebase origin {{index .PromptResponses 0}}"
    prompts:
      - type: 'input'
        title: 'What is the target branch to pull to your branch'
        initialValue: 'master'
