os:
  # edit: 'nvr -O $(pwd)/{{filename}}'
  # editAtLine: 'nvr -O +{{line}} $(pwd)/{{filename}}'
  # edit: 'nvr --remote-send "<F1>:e $(pwd)/{{filename}}<cr>"'
  # edit: 'nvr -c "FloatermHide" && nvr -c "e $(pwd)/{{filename}}"'
  # edit: 'nvr -c "FloatermHide" && nvr --remote-send ":e {{filename}}<cr>"'
  edit: 'nvr -c "FloatermHide" && nvr -c "e {{filename}}"'
  editAtLine: 'nvr -c "FloatermHide" && nvr -c "e +{{line}} {{filename}}"'
gui:
  theme:
    selectedLineBgColor:
      - default
customCommands:
  - key: 'C'
    prompts:
      - type: 'input'
        title: 'What is the new branch name?'
        initialValue: 'tom.levt/feat/'
    context: 'localBranches'
    description: 'Checkout under your name'
    command: "git checkout -b {{index .PromptResponses 0}}"
  - key: 'F'
    context: 'global'
    description: 'Pull the latest target branch to your branch'
    command: "git pull --rebase origin {{index .PromptResponses 0}}"
    prompts:
      - type: 'input'
        title: 'What is the target branch to pull to your branch'
        initialValue: 'master'
