os:
  # edit: 'nvr -O $(pwd)/{{filename}}'
  # editAtLine: 'nvr -O +{{line}} $(pwd)/{{filename}}'
  # edit: 'nvr --remote-send "<F1>:e $(pwd)/{{filename}}<cr>"'
  # edit: 'nvr -c "FloatermHide" && nvr -c "e $(pwd)/{{filename}}"'
  # edit: 'nvr -c "FloatermHide" && nvr --remote-send ":e {{filename}}<cr>"'
  edit: 'nvr -c "FloatermHide" && nvr -c "e {{filename}}"'
  editAtLine: 'nvr -c "FloatermHide" && nvr -c "e +{{line}} {{filename}}"'
gui:
  theme:
    selectedLineBgColor:
      - default
customCommands:
  - key: 'C'
    context: 'localBranches'
    # prompts:
    #   - type: 'menu'
    #     title: 'What kind of branch is it?'
    #     key: 'BranchType'
    #     options:
    #       - name: 'ta'
    #         description: 'Team Assurance Branch'
    #         value: 'TA'
    #       - name: 'feature'
    #         description: 'A feature branch'
    #         value: 'tom.levt/feat/'
    #       - name: 'fix'
    #         description: 'A fix branch'
    #         value: 'tom.levt/fix/'
    #   - type: 'input'
    #     title: 'What is the new branch name?'
    #     key: 'BranchName'
    #     initialValue: ''
    # command: "git checkout -b {{.Form.BranchType}}{{.Form.BranchName}}"
    loadingText: 'Creating branch'
    prompts:
      - type: 'input'
        title: 'What is the new branch name?'
        initialValue: 'tom.levt/feat/'
    description: 'Checkout under your name'
    command: "git checkout -b {{index .PromptResponses 0}}"
  - key: 'C'
    context: 'files'
    loadingText: 'Creating commit'
    prompts:
      - type: 'input'
        title: 'What is the new commit'
        key: 'CommitName'
        initialValue: 'feat:'
    description: 'Shortcut commit'
    command: "git commit -m '{{.Form.CommitName}}'"
  - key: 'F'
    context: 'global'
    description: 'Pull the latest target branch to your branch'
    command: "git pull --rebase origin {{index .PromptResponses 0}}"
    prompts:
      - type: 'input'
        title: 'What is the target branch to pull to your branch'
        initialValue: 'master'
